### ISSUE TITLE
Model performance

### ISSUE THREAD

**Issue by djanibekov** [vs-sat-dev/Body-performance-Aliftech-test-task-#2]
You wrote in the comment that there is no way of improving the accuracy for this task. Did you try to use one-vs-all approach?

**Comment by vs-sat-dev** [comment]
No. I'll read about it and try it today. Thank you.

**Comment by vs-sat-dev** [comment]
After looking at results for b_vs_all_dataframe this approach doesn't seem reasonable for this dataset.

**Comment by vs-sat-dev** [comment]
I made mistake with b_vs_all_df. I changed it and try one-vs-all approach with XGBoost model. It got me a little worse result. But the approach was interesting. Thank you for the idea.
